name: build github page
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install yarn
      - run: yarn install
      - run: yarn run build:preview
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        secrets:
          GH_PAT: ${{ secrets.GH_PAT }}
        env:
          BUILD_DIR: .
